[dev]
environment = { VITE_API_BASE = "/.netlify/functions" }
command = "npm start"

[build]
environment = { VITE_API_BASE = "/.netlify/functions" }
command = "npm run build"

[context.deploy-preview.environment]
REACT_APP_BUILD_VERSION = 'alpha'

[context.branch-deploy.environment]
REACT_APP_BUILD_VERSION = 'alpha'
